### ISSUE TITLE
Color fire history plots by species?

### ISSUE THREAD

**Issue by brews** [ltrr-arizona-edu/fhxR#4]
Is there some way to bring in species data (associated with an ID in an fhx object) then use the species data to color the default fire history plot?

**Comment by kmackjames** [comment]
Ahh! I have been trying to make this happen. I'll check out your code. Thanks :)

**Comment by brews** [comment]
Hey @kmackjames! Yeah, Ellis Margolis asked me to put a couple features in.

If I were you I'd wait a few days before you download anything. Right now these new features are still in the developing branch. I'm also adding support for rugs (lines on the bottoms of the plot). A few other features may also sneak in. Once I'm done adding those features and adding them in the wiki tutorial, I'll push it to the master branch and tag it as the first major release (with basic features). You should get a notification.

**Comment by kmackjames** [comment]
Sounds great.
